# Autogenerated by nbdev

d = { 'settings': { 'branch': 'dev',
                'doc_baseurl': '/nbdev_example',
                'doc_host': 'https://PaoloBova.github.io',
                'git_url': 'https://github.com/PaoloBova/nbdev_example',
                'lib_path': 'nbdev_example'},
  'syms': {'nbdev_example.core': {'nbdev_example.core.generate_crd': ('core.html#generate_crd', 'nbdev_example/core.py')}}}